ASoC: codecs: fix sprintf warning in wcd_cpe_core
../techpack/audio/asoc/codecs/wcd_cpe_core.c:1981:2: error: 'snprintf' size argument is too large; destination buffer has size 11, but size argument is 13 [-Werror,-Wfortify-source]
        snprintf(proc_name, (sizeof("cpe") + sizeof("_state") +
        ^
1 error generated.

Change-Id: Ibaf66e123c3f7c0fe710a99ce3e6d99df6aed130
(cherry picked from commit 9109f7631a235ae9eaf7cf630376069a07cd3c57)